In [1]:
## importing packages

import pandas as pd
import numpy as np

In [2]:
# reading the data from csv files

bigkart_newsales_df = pd.read_csv('bigkart_newsales.csv')
bigkart_sales_df = pd.read_csv('bigkart_sales.csv')

In [3]:
bigkart_newsales_df.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
1,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",0.0,288,20,2,Furniture,Bookcases
2,AZ-2011-1916555,"Eldon Folders, Single Width",0.4,61,7,6,Office Supplies,Storage
3,AZ-2011-1930058,"Sanford Markers, Easy-Erase",0.0,71,1,3,Office Supplies,Art
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories

In [4]:
bigkart_sales_df.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1029887,"Novimex Color Coded Labels, 5000 Label Set",0.0,26,7,2,Office Supplies,Labels
1,AZ-2011-107716,"Deflect-O Door Stop, Erganomic",0.0,85,15,2,Furniture,Furnishings
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
4,AZ-2011-1362199,"Sanford Pens, Fluorescent",0.5,25,-11,4,Office Supplies,Art

### Question 1: 

Some of the orders are stored in another csv file named `bigkart_newsales`. Read the csv file, store it in a data frame and add it to the `bigkart_sales` data frame. Find the total sales value of the category 'Office Supplies' after combining the dataframes

In [5]:
## combining / appending both bigkart_newsales_df & bigkart_sales_df

final_sales_df = pd.concat([bigkart_newsales_df, bigkart_sales_df]).reset_index(drop=True)
final_sales_df

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
1,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",0.0,288,20,2,Furniture,Bookcases
2,AZ-2011-1916555,"Eldon Folders, Single Width",0.4,61,7,6,Office Supplies,Storage
3,AZ-2011-1930058,"Sanford Markers, Easy-Erase",0.0,71,1,3,Office Supplies,Art
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories
...,...,...,...,...,...,...,...,...
63,AZ-2011-1474073,"Wilson Jones Hole Reinforcements, Recycled",0.0,10,2,2,Office Supplies,Binders
64,AZ-2011-1645475,"BIC Highlighters, Fluorescent",0.5,30,-10,3,Office Supplies,Art
65,AZ-2011-1735855,"Deflect-O Photo Frame, Black",0.0,156,34,3,Furniture,Furnishings
66,AZ-2011-1754604,"Avery Binding Machine, Economy",0.0,98,12,2,Office Supplies,Binders
67,AZ-2011-176674,"Hoover Microwave, Red",0.1,1667,185,6,Office Supplies,Appliances

In [6]:
# subsetting 'Office Supplies' category and take the sume of Sales

office_sipplies_sales = final_sales_df[final_sales_df['Category']=='Office Supplies']['Sales'].sum()
print('Total Sales value of the category "Office Supplies" is ₹{}'.format(office_sipplies_sales))

Total Sales value of the category "Office Supplies" is ₹7970

### Question 2: 

There are some duplicate rows in the data frame. Drop these rows and calculate the total sales value of the category Office Supplies.

In [7]:
# drop duplicated rows

final_sales_df = final_sales_df.drop_duplicates().reset_index(drop=True)
final_sales_df

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
1,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",0.0,288,20,2,Furniture,Bookcases
2,AZ-2011-1916555,"Eldon Folders, Single Width",0.4,61,7,6,Office Supplies,Storage
3,AZ-2011-1930058,"Sanford Markers, Easy-Erase",0.0,71,1,3,Office Supplies,Art
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories
...,...,...,...,...,...,...,...,...
56,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones
57,AZ-2011-1723003,"Ibico Index Tab, Clear",0.0,18,3,2,Office Supplies,Binders
58,AZ-2011-1735855,"Deflect-O Photo Frame, Black",0.0,156,34,3,Furniture,Furnishings
59,AZ-2011-1754604,"Avery Binding Machine, Economy",0.0,98,12,2,Office Supplies,Binders
60,AZ-2011-176674,"Hoover Microwave, Red",0.1,1667,185,6,Office Supplies,Appliances

In [8]:
office_sipplies_sales = final_sales_df[final_sales_df['Category']=='Office Supplies']['Sales'].sum()
print('Total Sales value of the category "Office Supplies" after dropping duplicated rows is ₹{}'.format(office_sipplies_sales))

Total Sales value of the category "Office Supplies" after dropping duplicated rows is ₹6964

### Question 3:

Find the most profitable category and sub category combination based on the net profit.

In [9]:
# groupby Category & Sub-Category columns and take sum of profit

cat_subcat_profit_gb = final_sales_df.groupby(['Category', 'Sub-Category']).agg({'Profit':'sum'}).reset_index()

# sorting the values based on total profit combined Category & Sub Category
most_profit_cat_subcat = cat_subcat_profit_gb.sort_values(by='Profit', ascending=False).reset_index(drop=True).head()
most_profit_cat_subcat

          Category Sub-Category  Profit
0       Technology       Phones    1618
1        Furniture    Bookcases     308
2  Office Supplies          Art     275
3  Office Supplies   Appliances     229
4       Technology  Accessories     215

In [10]:
print('{} - {} are the most profitable category and sub category combination with net profit of ₹{}, \nwhen compared to others'.format(most_profit_cat_subcat['Category'][0], most_profit_cat_subcat['Sub-Category'][0], most_profit_cat_subcat['Profit'][0]))

Technology - Phones are the most profitable category and sub category combination with net profit of ₹1618,
when compared to others

### Question 4: 

How many invalid order IDs are there in the data frame. An order id is of the form AZ-2011-Y where Y represents a whole number. A Order ID is said to be valid only if Y consists of 7 digits. Find the number of invalid order order IDs in the data frame.

In [11]:
# split the order ID based on "-" (delimiter), which outputs list of strings, then index the last string from the list and 
# take length of string to validate if the oder id is valid or invalid
final_sales_df['order_id_val_check'] = final_sales_df['Order ID'].apply(lambda x: x.split("-")[-1]).str.len()

# create datafatme, take count of values based on newly created column 'order_id_val_check' and renaming them 
coun_val_inval_df = final_sales_df['order_id_val_check'].value_counts().reset_index().rename(columns = {'index': 'len_oder_id', 'order_id_val_check':'count_val_inval'})
coun_val_inval_df

   len_oder_id  count_val_inval
0            7               54
1            6                7

In [12]:
print('{} Order IDs are invalid of {}' .format(coun_val_inval_df[coun_val_inval_df['len_oder_id']==6]['count_val_inval'][1], len(final_sales_df)))

7 Order IDs are invalid of 61

### Question 5:

Find the top 25 orders based on sales value and find the number of orders which belong to furniture category.

In [13]:
print('Below are the Top 25 orders based on Sales value')

final_sales_df.sort_values(by='Sales', ascending=False).reset_index(drop=True)[['Order ID', 'Product Name','Sales', 'Profit', 'Quantity']].head(25)

Below are the Top 25 orders based on Sales value

,Order ID,Product Name,Sales,Profit,Quantity
0,AZ-2011-1410648,"Nokia Smart Phone, Full Size",1908,820,3
1,AZ-2011-176674,"Hoover Microwave, Red",1667,185,6
2,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",1334,200,8
3,AZ-2011-1322840,"Motorola Headset, with Caller ID",957,316,12
4,AZ-2011-1372644,"Panasonic Printer, Durable",800,168,3
5,AZ-2011-1406494,"Fellowes Lockers, Industrial",748,283,4
6,AZ-2011-1536006,"Logitech Keyboard, Programmable",666,66,9
7,AZ-2011-1445262,"Apple Smart Phone, Cordless",636,140,1
8,AZ-2011-144325,"Bush Stackable Bookrack, Pine",630,132,5
9,AZ-2011-1260928,"Eldon File Cart, Single Width",576,51,5
10,AZ-2011-1253407,"Safco Stackable Bookrack, Pine",541,156,4
11,AZ-2011-1672552,"Binney & Smith Sketch Pad, Blue",510,132,11
12,AZ-2011-1584049,"Brother Ink, Laser",442,0,3
13,AZ-2011-1722024,"Cisco Audio Dock, VoIP",364,142,2
14,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",339,102,7
15,AZ-2011-130330,"Office Star Chairmat, Adjustable",307,99,5
16,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",294,109,7
17,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",288,20,2
18,AZ-2011-1240916,"Boston Canvas, Water Color",284,43,5
19,AZ-2011-145488,"Rogers File Cart, Industrial",255,-98,3
20,AZ-2011-1116129,"Avery Binding Machine, Durable",252,15,5
21,AZ-2011-1584987,"Tenex File Cart, Industrial",241,24,2
22,AZ-2011-1499597,"Boston Markers, Fluorescent",193,29,7
23,AZ-2011-1655349,"Fiskars Trimmer, Easy Grip",176,65,4
24,AZ-2011-1589827,"Novimex Steel Folding Chair, Red",164,-70,5

In [14]:
print('There are {} orders that belong to Category "Furniture"' .format(len(final_sales_df[final_sales_df['Category'] == 'Furniture'])))

There are 11 orders that belong to Category "Furniture"

### Question 6: 

Among the orders with sales>250 and profit>50, find the product name of the fourth highest order based on sales value.

In [15]:
# subset the dataframe with Sales>250 & Profit>50, sort descending based on Sales 

prod_four_high = final_sales_df[(final_sales_df['Sales']>250)&(final_sales_df['Profit']>50)].sort_values(by='Sales', ascending=False).reset_index(drop=True)

print('Among the orders with sales>250 and profit>50, "\033[1m{}\033[0m" is fourth highest order based on sales value.' .format(prod_four_high.loc[3, 'Product Name']))

Among the orders with sales>250 and profit>50, "Motorola Headset, with Caller ID" is fourth highest order based on sales value.

### Question 7: 

Remove the orders with negative profit by dropping the corresponding rows with negative `Profit`. Find the product that makes the lowest profit per Quantity in the Technology category.

In [16]:
# remove the profits with negative value, subset Technology Category and order values ascending based on Profit

non_neg_prof_tech_cat_df = final_sales_df[(final_sales_df['Profit']>=0)&(final_sales_df['Category']=='Technology')].sort_values('Profit').reset_index(drop=True)
non_neg_prof_tech_cat_df

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category,order_id_val_check
0,AZ-2011-1584049,"Brother Ink, Laser",0.0,442,0,3,Technology,Copiers,7
1,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories,7
2,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories,7
3,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories,7
4,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones,7
5,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones,7
6,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines,7
7,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones,7
8,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones,7
9,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones,7

In [17]:
print('\033[1m{}\033[0m is the product with least Profit value of \033[1m₹{}\033[0m amoung Category Technology'.format(non_neg_prof_tech_cat_df.loc[0, 'Product Name'], non_neg_prof_tech_cat_df.loc[0, 'Profit']))

Brother Ink, Laser is the product with least Profit value of ₹0 amoung Category Technology